import { describe, expect, it } from 'vitest'
import { applyEvent, defenderOrder, initialState, replay } from './engine'
import { finalize } from './finalize'
import { fraction } from './fraction'
import { deserializeGame, serializeGame } from './persistence'
import type { GameConfig, GameEvent, NormalHandEvent, SavedGame } from './types'

const config = (count: 3 | 4 = 3, target = 100): GameConfig => ({ schemaVersion: 1, createdAt: '2026-01-01T00:00:00Z', players: ['A', 'B', 'C', 'D'].slice(0, count).map(id => ({ id, name: id })), poolTarget: target, euroCentsPerCredit: 1, firstRestPlayerId: count === 4 ? 'D' : undefined, animations: true })
const normal = (overrides: Partial<NormalHandEvent> = {}): NormalHandEvent => ({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), type: 'normal', declarerId: 'A', level: 6, suit: 'picche', defenderChoices: { B: 'pass', C: 'vist' }, tricks: { A: 6, B: 0, C: 4 }, ...overrides })

describe('contratti normali', () => {
  it('calcola un vistante su 6 riuscito', () => { const s = applyEvent(initialState(config()), normal()); expect(s.scores.A.pool).toBe(2); expect(s.credits.C.A).toEqual(fraction(8)); expect(s.scores.C.penalty).toBe(0) })
  it('calcola difesa corta con unico vistante', () => { const s = applyEvent(initialState(config()), normal({ tricks: { A: 7, B: 1, C: 2 } })); expect(s.scores.A.pool).toBe(2); expect(s.credits.C.A).toEqual(fraction(6)); expect(s.scores.C.penalty).toBe(2) })
  it('calcola fallimento su 8', () => { const s = applyEvent(initialState(config()), normal({ level: 8, tricks: { A: 6, B: 1, C: 3 } })); expect(s.scores.A.penalty).toBe(12); expect(s.credits.C.A).toEqual(fraction(24)) })
  it('separa responsabilità di due vistanti su 6', () => { const s = applyEvent(initialState(config()), normal({ defenderChoices: { B: 'vist', C: 'vist' }, tricks: { A: 8, B: 1, C: 1 } })); expect(s.scores.A.pool).toBe(2); expect(s.credits.B.A).toEqual(fraction(2)); expect(s.credits.C.A).toEqual(fraction(2)); expect(s.scores.B.penalty).toBe(2); expect(s.scores.C.penalty).toBe(2) })
  it('su 8 rende responsabile solo il secondo difensore', () => { const s = applyEvent(initialState(config()), normal({ level: 8, defenderChoices: { B: 'vist', C: 'vist' }, tricks: { A: 9, B: 1, C: 0 } })); expect(s.scores.A.pool).toBe(6); expect(s.credits.B.A).toEqual(fraction(6)); expect(s.credits.C.A).toEqual(fraction(0)); expect(s.scores.B.penalty).toBe(0); expect(s.scores.C.penalty).toBe(6) })
  it('calcola polvist con tetto e deficit', () => { const full = applyEvent(initialState(config()), normal({ defenderChoices: { B: 'pass', C: 'polvist' } })); expect(full.credits.C.A).toEqual(fraction(4)); const short = applyEvent(initialState(config()), normal({ defenderChoices: { B: 'pass', C: 'polvist' }, tricks: { A: 9, B: 0, C: 1 } })); expect(short.credits.C.A).toEqual(fraction(2)); expect(short.scores.C.penalty).toBe(2) })
  it('gestisce il contratto 10 con zero o una presa difensiva', () => { const made = applyEvent(initialState(config()), normal({ level: 10, tricks: { A: 10, B: 0, C: 0 } })); expect(made.scores.A.pool).toBe(10); expect(made.scores.C.penalty).toBe(10); const failed = applyEvent(initialState(config()), normal({ level: 10, tricks: { A: 9, B: 0, C: 1 } })); expect(failed.scores.A.penalty).toBe(10); expect(failed.credits.C.A).toEqual(fraction(10)) })
  it('rifiuta polvist illegale e prese non pari a dieci', () => { expect(() => applyEvent(initialState(config()), normal({ level: 8, defenderChoices: { B: 'pass', C: 'polvist' } }))).toThrow(/non ammessa/); expect(() => applyEvent(initialState(config()), normal({ tricks: { A: 6, B: 1, C: 1 } }))).toThrow(/sommar/) })
})

describe('mizer, raspasy e aiuto americano', () => {
  it('calcola mizer', () => { const zero = applyEvent(initialState(config()), { id: 'm0', createdAt: '', type: 'mizer', declarerId: 'A', declarerTricks: 0 }); expect(zero.scores.A.pool).toBe(10); const two = applyEvent(initialState(config()), { id: 'm2', createdAt: '', type: 'mizer', declarerId: 'A', declarerTricks: 2 }); expect(two.scores.A.penalty).toBe(20) })
  it('applica amnistia e progressione raspasy', () => { const e = (id: string): GameEvent => ({ id, createdAt: '', type: 'raspasy', tricks: { A: 2, B: 5, C: 3 } }); const s1 = applyEvent(initialState(config()), e('r1')); expect([s1.scores.A.penalty, s1.scores.B.penalty, s1.scores.C.penalty]).toEqual([0, 3, 1]); const s2 = applyEvent(s1, e('r2')); expect([s2.scores.A.penalty, s2.scores.B.penalty, s2.scores.C.penalty]).toEqual([0, 9, 3]) })
  it('premia lo zero nel secondo raspasy', () => { const first: GameEvent = { id: 'r1', createdAt: '', type: 'raspasy', tricks: { A: 2, B: 5, C: 3 } }; const second: GameEvent = { id: 'r2', createdAt: '', type: 'raspasy', tricks: { A: 0, B: 4, C: 6 } }; const s = replay(config(), [first, second]); expect(s.scores.A.pool).toBe(1); expect(s.scores.B.penalty).toBe(11); expect(s.scores.C.penalty).toBe(13) })
  it('non resetta con entrambi passanti ma resetta con vist e mizer', () => { const r: GameEvent = { id: 'r', createdAt: '', type: 'raspasy', tricks: { A: 2, B: 5, C: 3 } }; const passes = normal({ id: 'p', defenderChoices: { B: 'pass', C: 'pass' }, tricks: undefined }); expect(replay(config(), [r, passes]).raspasyLevel).toBe(2); expect(replay(config(), [r, normal()]).raspasyLevel).toBe(1); expect(replay(config(), [r, { id: 'm', createdAt: '', type: 'mizer', declarerId: 'A', declarerTricks: 1 }]).raspasyLevel).toBe(1) })
  it('distribuisce aiuto per Pozzo più alto e poi ordine orario', () => { const c = config(3, 3); const seeded = replay(c, [{ id: 'x', createdAt: '', type: 'manual', adjustments: [{ kind: 'pool', playerId: 'A', amount: 3 }, { kind: 'pool', playerId: 'B', amount: 2 }] }]); const s = applyEvent(seeded, { id: 'y', createdAt: '', type: 'manual', adjustments: [{ kind: 'pool', playerId: 'A', amount: 2 }] }); expect([s.scores.B.pool, s.scores.C.pool]).toEqual([3, 1]); expect(s.credits.A.B).toEqual(fraction(10)); expect(s.credits.A.C).toEqual(fraction(10)) })
  it('riduce la Multa con eccedenza quando tutti i Pozzi sono chiusi', () => { const c = config(3, 3); const s = replay(c, [{ id: 'seed', createdAt: '', type: 'manual', adjustments: [{ kind: 'pool', playerId: 'A', amount: 3 }, { kind: 'pool', playerId: 'B', amount: 3 }, { kind: 'pool', playerId: 'C', amount: 3 }, { kind: 'penalty', playerId: 'A', amount: 2 }] }, { id: 'extra', createdAt: '', type: 'manual', adjustments: [{ kind: 'pool', playerId: 'A', amount: 3 }] }]); expect(s.scores.A.penalty).toBe(0); expect(s.scores.A.pool).toBe(3) })
})

describe('quattro giocatori, replay e finalizzazione', () => {
  it('calcola l’ordine difensori e ruota il riposo con override', () => { const c = config(4); expect(defenderOrder(c, ['A', 'B', 'C'], 'C')).toEqual(['A', 'B']); const e = normal({ restPlayerId: 'D' }); const s = applyEvent(initialState(c), e); expect(s.nextRestPlayerId).toBe('A'); const s2 = applyEvent(s, normal({ id: 'n2', restPlayerId: 'B', declarerId: 'A', defenderChoices: { C: 'pass', D: 'pass' }, tricks: undefined })); expect(s2.nextRestPlayerId).toBe('C') })
  it('può aiutare chi riposa', () => { const c = config(4, 3); const s = replay(c, [{ id: 'seed', createdAt: '', type: 'manual', adjustments: [{ kind: 'pool', playerId: 'A', amount: 3 }, { kind: 'pool', playerId: 'B', amount: 3 }, { kind: 'pool', playerId: 'C', amount: 3 }] }, normal({ restPlayerId: 'D', defenderChoices: { B: 'pass', C: 'pass' }, tricks: undefined })]); expect(s.scores.D.pool).toBe(2); expect(s.credits.A.D).toEqual(fraction(20)) })
  it('ricalcola in modo deterministico dopo modifica o eliminazione', () => { const events = [normal({ id: '1' }), { id: '2', createdAt: '', type: 'raspasy', tricks: { A: 2, B: 5, C: 3 } } as GameEvent]; const original = replay(config(), events); const modified = replay(config(), [normal({ id: '1', defenderChoices: { B: 'pass', C: 'pass' }, tricks: undefined }), events[1]!]); expect(modified.raspasyLevel).toBe(2); expect(original.applied.length).toBe(2); expect(replay(config(), [events[1]!]).applied.length).toBe(1) })
  it('applica esattamente la Multa finale a 3 e 4', () => { const s3 = replay(config(), [{ id: 'p', createdAt: '', type: 'manual', adjustments: [{ kind: 'penalty', playerId: 'A', amount: 2 }, { kind: 'penalty', playerId: 'B', amount: 5 }, { kind: 'penalty', playerId: 'C', amount: 8 }] }]); const f3 = finalize(s3); expect(f3.minimumPenalty).toBe(2); expect(f3.penaltyCredits.find(x => x.fromId === 'A' && x.againstId === 'B')?.amount).toEqual(fraction(15)); expect(f3.penaltyCredits.find(x => x.fromId === 'A' && x.againstId === 'C')?.amount).toEqual(fraction(30)); const s4 = replay(config(4), [{ id: 'p', createdAt: '', type: 'manual', adjustments: [{ kind: 'penalty', playerId: 'D', amount: 3 }] }]); expect(finalize(s4).penaltyCredits.filter(x => x.againstId === 'D').map(x => x.amount)).toEqual([fraction(10), fraction(10), fraction(10)]) })
  it('bilancia centesimi e settlement', () => { const s = replay({ ...config(4), euroCentsPerCredit: 1 }, [{ id: 'p', createdAt: '', type: 'manual', adjustments: [{ kind: 'penalty', playerId: 'D', amount: 1 }] }]); const f = finalize(s); expect(f.players.reduce((n, p) => n + p.euroCents, 0)).toBe(0); const balances: Record<string, number> = Object.fromEntries(f.players.map(p => [p.playerId, 0])); f.payments.forEach(p => { balances[p.fromId]! -= p.cents; balances[p.toId]! += p.cents }); f.players.forEach(p => expect(balances[p.playerId]).toBe(p.euroCents)) })
  it('serializza e ripristina lo schema versionato', () => { const saved: SavedGame = { schemaVersion: 1, config: config(), events: [normal()], undone: [], updatedAt: '' }; expect(deserializeGame(serializeGame(saved))).toEqual(saved); expect(() => deserializeGame('{"schemaVersion":2}')).toThrow(/supportata/) })
  it('chiude una partita completa a tre giocatori', () => { const c = config(3, 2); const events: GameEvent[] = ['A', 'B', 'C'].map((declarerId, i) => { const [d1, d2] = defenderOrder(c, ['A', 'B', 'C'], declarerId); return normal({ id: `full3-${i}`, declarerId, defenderChoices: { [d1]: 'pass', [d2]: 'pass' }, tricks: undefined }) }); const s = replay(c, events); expect(s.completed).toBe(true); expect(c.players.map(p => s.scores[p.id]!.pool)).toEqual([2, 2, 2]) })
  it('chiude una partita completa a quattro rispettando tutta la rotazione', () => { const c = { ...config(4, 2), firstRestPlayerId: 'D' }; const rests = ['D', 'A', 'B', 'C']; const declarers = ['A', 'B', 'C', 'D']; const events: GameEvent[] = declarers.map((declarerId, i) => { const active = c.players.map(p => p.id).filter(id => id !== rests[i]); const [d1, d2] = defenderOrder(c, active, declarerId); return normal({ id: `full4-${i}`, restPlayerId: rests[i], declarerId, defenderChoices: { [d1]: 'pass', [d2]: 'pass' }, tricks: undefined }) }); const s = replay(c, events); expect(s.completed).toBe(true); expect(s.nextRestPlayerId).toBe('D'); expect(s.applied.map(a => a.restPlayerId)).toEqual(rests) })
})
