export interface ManualSection { id: string; title: string; tags: string[]; body: string[]; table?: string[][] }
export const manualSections: ManualSection[] = [
  { id: 'convenzioni', title: '1. Convenzioni adottate', tags: ['base'], body: ['Preferans Score applica esclusivamente la variante Soči personalizzata descritta qui. Registra il contratto finale e non ricostruisce l’asta. Una mano è una distribuzione; la partita è l’intera sessione fino alla chiusura di tutti i Pozzi.', 'La difesa usa il vist responsabile e il conteggio “egoista”: con due vistanti ciascuno riceve Crediti sulle proprie prese. Non si applicano né consolazione al passante né Stalingrad. Il polvist è quello giocato.', 'In ogni mano giocata ci sono esattamente tre giocatori attivi e le loro prese sommano a 10.'] },
  { id: 'terminologia', title: '2. Terminologia', tags: ['base'], body: ['Pozzo: punti positivi verso l’obiettivo; nei manuali tradizionali può chiamarsi Pula. Multa: penalità, detta anche Montagna o Gora. Crediti: rapporti direzionali fra coppie, tradizionalmente annotati nella zona del vist.', 'Il dichiarante gioca il contratto; i difensori scelgono pass, vist o, quando ammesso, polvist. Un passante rimane un giocatore attivo della mano giocata, ma non riceve Crediti.'] },
  { id: 'foglio', title: '3. Struttura del foglio di punteggio', tags: ['base'], body: ['Il foglio mostra Pozzo e Multa di ciascuno e ogni relazione “A possiede Crediti contro B”. A tre è triangolare; a quattro è disposto a diamante. I Crediti non sono un saldo unico: restano direzionali fino al calcolo finale.'] },
  { id: 'valori', title: '4. Valori e ordine dei contratti', tags: ['contratto'], body: ['Ordine: 6, 7, 8, Mizer (fra 8 senza briscola e 9 picche), 9, 10. A pari livello: picche, fiori, quadri, cuori, senza briscola. Per esempio: 6 picche < 6 fiori < 6 quadri < 6 cuori < 6 senza briscola < 7 picche.', 'Il seme documenta il contratto ma non cambia il suo valore numerico.'], table: [['Livello', '6', '7', '8', '9', '10'], ['Valore', '2', '4', '6', '8', '10']] },
  { id: 'tipi', title: '5. Tipi di mano', tags: ['base'], body: ['Si registra un contratto normale quando qualcuno dichiara da 6 a 10, un Mizer quando quello è il contratto finale, oppure un Raspasy quando tutti e tre passano subito in asta. Una correzione manuale è un evento contabile e non una mano giocata.', 'Raspasy, Mizer, vist e polvist producono una mano giocata. Un contratto seguito da due pass non viene materialmente giocato. Il salvataggio applica tutte le variazioni in modo atomico.'] },
  { id: 'normale', title: '6. Contratto normale', tags: ['contratto'], body: ['Il dichiarante mantiene se raggiunge il livello: il valore entra nel Pozzo tramite aiuto americano. Se fallisce, prese mancanti × valore vanno in Multa. Le prese in più non danno bonus.', 'Se entrambi i difensori passano la mano non è giocata: il contratto è automaticamente riuscito, i difensori ottengono zero e i Raspasy non si azzerano.', 'Stalingrad non si usa: anche su 6 picche i difensori scelgono liberamente pass, vist o polvist quando quest’ultimo è ammesso.'] },
  { id: 'obblighi', title: '7. Obblighi dei difensori', tags: ['vist'], body: ['Con un solo vistante la difesa deve prendere 4 contro 6, 2 contro 7, 1 contro 8, 9 e 10. La carenza moltiplicata per il valore va nella Multa del vistante.'], table: [['Contratto', '6', '7', '8', '9', '10'], ['Obbligo totale', '4', '2', '1', '1', '1']] },
  { id: 'vistanti', title: '8. Uno o due vistanti', tags: ['vist'], body: ['Un vistante riceve totale prese della difesa × valore, comprese le prese del passante. Con due vistanti ognuno riceve proprie prese × valore.', 'Esempio su 7: A mantiene con 7 prese, B prende 1 e C prende 2; A riceve 4 Pozzo, B 4 Crediti contro A e C 8 Crediti contro A.', 'Con due vistanti su 6 ciascuno risponde di 2 prese; su 7 di 1. Su 8, 9 e 10 risponde di 1 presa soltanto il secondo difensore.'] },
  { id: 'passante', title: '9. Passante e assenza di consolazione', tags: ['vist'], body: ['Il passante riceve sempre zero Crediti, anche se prende materialmente prese e anche quando il dichiarante fallisce. Non esistono consolazioni o bonus automatici per il fallimento.'] },
  { id: 'polvist', title: '10. Polvist giocato', tags: ['polvist'], body: ['Solo su 6 o 7, dopo il pass del primo difensore, il secondo può scegliere polvist. La mano si gioca e azzera i Raspasy. Il polvist classico non giocato non appartiene a questa variante.', 'Su 6 la quota è 2, su 7 è 1. Crediti = min(prese totali difesa, quota) × valore; Multa = max(0, quota − prese totali difesa) × valore. Il massimo è 4 Crediti.', 'Esempio su 6: con 4 prese totali della difesa il polvistante riceve comunque soltanto 2 × 2 = 4 Crediti. Con una sola presa riceve 2 Crediti e scrive 2 Multa.'] },
  { id: 'dieci', title: '11. Contratto da 10', tags: ['contratto', 'vist'], body: ['Non è automaticamente aperto. Con due pass il dichiarante riceve 10 Pozzo. Con almeno un vist si gioca e l’obbligo difensivo è 1.', 'Esempi: 10 prese contro un vist → +10 Pozzo e vistante +10 Multa; 9 prese → dichiarante +10 Multa e vistante +10 Crediti; 8 prese → +20 Multa e +20 Crediti.'] },
  { id: 'mizer', title: '12. Mizer', tags: ['mizer'], body: ['Vale 10, senza briscola, senza vist o polvist. Zero prese danno +10 Pozzo; ogni presa costa 10 Multa. È sempre giocato e azzera i Raspasy.', 'In asta è ammesso soltanto come prima dichiarazione personale e si colloca fra 8 senza briscola e 9 picche. Può quindi essere la prima dichiarazione di B anche se A ha già dichiarato 6 picche; non è valido se B aveva già passato o dichiarato un contratto normale.', 'L’app riceve il contratto finale e non ricostruisce né valida l’intera asta.'] },
  { id: 'raspasy', title: '13. Raspasy progressivi e amnistia', tags: ['raspasy'], body: ['Quando tutti passano subito, il valore per presa è 1, poi 2, poi 3 e resta 3. Si sottrae il minimo delle prese della mano: Multa = (prese personali − minimo) × livello. Tutti i giocatori a pari merito con il minimo ricevono zero.', 'Un contratto materialmente giocato con vist o polvist e il Mizer azzerano la progressione. Il doppio pass non la azzera perché la mano non viene giocata.'] },
  { id: 'zero', title: '14. Premio per zero prese', tags: ['raspasy', 'aiuto americano'], body: ['Ogni giocatore a zero nei Raspasy riceve sempre +1 Pozzo, a qualunque livello. Il punto passa attraverso l’aiuto americano.', 'Questa è una personalizzazione definitiva dell’app: il premio non cresce a 2 o 3 insieme al valore delle prese del Raspasy.'] },
  { id: 'quattro', title: '15. Quattro giocatori e riposo', tags: ['quattro giocatori'], body: ['Giocano sempre tre persone; una riposa. Il riposo avanza in senso orario dopo ogni mano, anche col doppio pass, e può essere cambiato prima del salvataggio. Il riposante è escluso dai punteggi diretti e dai Raspasy, ma può ricevere aiuto americano.', 'Dal dichiarante si percorrono i posti attivi in senso orario, saltando chi riposa: così si determinano primo e secondo difensore.'] },
  { id: 'americano', title: '16. Aiuto americano', tags: ['aiuto americano'], body: ['Un guadagno riempie prima il Pozzo del titolare. L’eccedenza va a chi è sotto obiettivo e ha il Pozzo più alto; a pari merito decide l’ordine orario a partire dal donatore.', 'Ogni punto trasferito genera 10 Crediti del donatore contro il destinatario. Quando tutti i Pozzi sono chiusi, l’eccedenza riduce la Multa del donatore 1:1 fino a zero; il resto è ignorato.'] },
  { id: 'chiusura', title: '17. Chiusura della partita', tags: ['finale'], body: ['La partita termina quando tutti, incluso l’eventuale quarto partecipante, raggiungono l’obiettivo. Undo o modifica possono riaprirla.'] },
  { id: 'multa-finale', title: '18. Calcolo finale della Multa', tags: ['calcolo finale'], body: ['Si sottrae a tutti la Multa minima. Ogni punto residuo vale 10 Crediti divisi esattamente fra tutti gli avversari: 5 ciascuno a tre; 10/3 ciascuno a quattro.', 'Esempio 2, 5, 8 → residui 0, 3, 6. B deve 15 ad A e C; C deve 30 ad A e B. Le frazioni restano esatte.'] },
  { id: 'pagamenti', title: '19. Crediti netti, euro e pagamenti', tags: ['calcolo finale'], body: ['Netto = Crediti posseduti − Crediti subiti. La somma è zero. Il valore in euro viene applicato senza arrotondamenti intermedi; i centesimi sono bilanciati deterministicamente e poi trasformati in una lista minima di pagamenti.'] },
  { id: 'esempi', title: '20. Esempi completi', tags: ['esempi'], body: ['Contratto 6: A prende 6, B passa, C vista e la difesa totalizza 4. A scrive 2 Pozzo; C possiede 8 Crediti contro A.', 'Contratto 8 con due vistanti: A prende 9, il primo difensore B prende 1 e il secondo C zero. A scrive 6 Pozzo; B riceve 6 Crediti; C riceve zero Crediti e scrive 6 Multa perché è il responsabile.', 'Polvist su 6: il primo difensore passa, il secondo dichiara polvist e la difesa prende 4. Il dichiarante mantenuto riceve 2 Pozzo; il polvistante riceve soltanto 4 Crediti.', 'Raspasy livello 2, prese 0–4–6: il primo riceve sempre +1 Pozzo; gli altri scrivono 8 e 12 Multa.'] },
  { id: 'formule', title: '21. Tabella rapida delle formule', tags: ['formule'], body: ['Tutte le formule operative sono riassunte qui.'], table: [['Evento', 'Formula'], ['Contratto fallito', '(livello − prese) × valore → Multa'], ['Un vistante', 'prese difesa × valore → Crediti'], ['Raspasy', '(prese − minimo) × livello → Multa'], ['Aiuto', '10 × punti trasferiti → Crediti'], ['Multa finale', 'residuo × 10 ÷ avversari']] }
]

export const beginnerSections = [
  { title: 'Il gioco in un minuto', text: 'Il Preferans è un gioco di prese con un mazzo di 32 carte, dal 7 all’asso. Tre persone giocano ogni mano: ricevono 10 carte ciascuna e 2 restano nel tallone. Si cerca di rispettare una promessa, detta contratto, oppure di prendere meno prese possibile.' },
  { title: 'Carte e prese', text: 'L’ordine è asso, re, donna, fante, 10, 9, 8, 7. Devi rispondere al seme giocato; se non puoi, devi usare una briscola; se non hai neppure briscole, puoi giocare qualsiasi carta. Vince la briscola più alta, oppure la carta più alta del seme iniziale.' },
  { title: 'Contratto e difesa', text: 'Il dichiarante promette da 6 a 10 prese. Gli altri sono difensori: pass significa non assumersi l’impegno, vist significa difendere, polvist è una difesa ridotta e giocata, ammessa solo al secondo difensore su 6 o 7 dopo il pass del primo.' },
  { title: 'Mizer e Raspasy', text: 'Nel Mizer il dichiarante vuole zero prese: riuscire vale 10 Pozzo, ogni presa costa 10 Multa. Nei Raspasy nessuno dichiara: tutti cercano poche prese e chi sta al minimo gode dell’amnistia.' },
  { title: 'Pozzo, Multa e Crediti', text: 'Il Pozzo avanza verso l’obiettivo, la Multa pesa sul risultato finale, i Crediti sono diritti diretti contro un avversario. Se guadagni oltre il tuo obiettivo, l’aiuto americano chiude i Pozzi altrui e ti dà 10 Crediti per punto aiutato.' },
  { title: 'Se siete in quattro', text: 'A ogni mano uno riposa. Il riposo gira in senso orario. Chi riposa non partecipa alla mano, ma può comunque ricevere aiuto americano.' },
  { title: 'Esempio normale', text: 'A dichiara 6 e prende 6. B passa, C vista; B e C fanno insieme 4 prese. A ottiene 2 Pozzo, C ottiene 8 Crediti contro A.' },
  { title: 'Esempio Mizer', text: 'A dichiara Mizer e non prende nulla: ottiene 10 Pozzo. Se avesse preso 2, avrebbe scritto 20 Multa.' },
  { title: 'Esempio Raspasy', text: 'Al primo Raspasy le prese sono 2, 5, 3. Il minimo è 2: le Multe sono quindi 0, 3, 1.' },
  { title: 'Chi paga chi?', text: 'Alla fine l’app compensa Crediti e Multa, converte il saldo in euro e mostra frasi semplici come “A paga €4,50 a B”. Gli importi sono bilanciati: quanto viene pagato è esattamente quanto viene ricevuto.' }
]
