import { useEffect, useMemo, useRef, useState } from 'react'
import { activePlayers, applyEvent, defenderOrder, replay } from './domain/engine'
import { finalize } from './domain/finalize'
import { formatFraction } from './domain/fraction'
import { deserializeGame, loadGame, saveGame, serializeGame, STORAGE_KEY } from './domain/persistence'
import type { AppliedEvent, DefenderChoice, GameConfig, GameEvent, GameState, HandType, ManualAdjustment, SavedGame, Suit } from './domain/types'
import { beginnerSections, manualSections } from './content/manual'
import { exportPdf } from './services/pdf'

const euro = (cents: number) => new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(cents / 100)
const uid = () => crypto.randomUUID()
const nameOf = (state: GameState, id?: string) => state.config.players.find(p => p.id === id)?.name ?? '—'
const signed = (n: number) => `${n > 0 ? '+' : ''}${n}`

function Setup({ onStart, initial, lockParticipants = false, onCancel }: { onStart: (c: GameConfig) => void; initial?: GameConfig; lockParticipants?: boolean; onCancel?: () => void }) {
  const [count, setCount] = useState<3 | 4>((initial?.players.length as 3 | 4) ?? 3)
  const [names, setNames] = useState(initial?.players.map(p => p.name) ?? ['Giocatore 1', 'Giocatore 2', 'Giocatore 3', 'Giocatore 4'])
  const [target, setTarget] = useState(initial?.poolTarget ?? 3); const [euros, setEuros] = useState(((initial?.euroCentsPerCredit ?? 1) / 100).toFixed(2)); const [rest, setRest] = useState(initial?.firstRestPlayerId ?? 'p4'); const [review, setReview] = useState(false)
  const players = Array.from({ length: count }, (_, i) => ({ id: initial?.players[i]?.id ?? `p${i + 1}`, name: names[i]?.trim() || `Giocatore ${i + 1}` }))
  const config: GameConfig = { schemaVersion: 1, createdAt: initial?.createdAt ?? new Date().toISOString(), players, poolTarget: target, euroCentsPerCredit: Math.round(Number(euros.replace(',', '.')) * 100), firstRestPlayerId: count === 4 ? (players.some(p => p.id === rest) ? rest : players[3]!.id) : undefined, animations: initial?.animations ?? true }
  const valid = players.every(p => p.name.trim()) && new Set(players.map(p => p.name.toLocaleLowerCase())).size === count && Number.isInteger(target) && target > 0 && config.euroCentsPerCredit >= 0
  return <main className="setup-page"><section className="setup-hero"><span className="suit-row" aria-hidden>♠ ♣ ♦ ♥</span><p className="eyebrow">Foglio di punteggio offline</p><h1>Preferans <em>Score</em></h1><p>La variante Soči personalizzata, pronta al tavolo.</p></section><section className="setup-panel" aria-labelledby="setup-title"><div className="step-kicker">{review ? 'Riepilogo' : 'Nuova partita'}</div><h2 id="setup-title">{review ? 'Tutto pronto?' : 'Prepara il tavolo'}</h2>{!review ? <>
    <fieldset><legend>Quanti partecipanti?</legend><div className="segmented"><button disabled={lockParticipants} className={count === 3 ? 'selected' : ''} onClick={() => setCount(3)}>3 giocatori</button><button disabled={lockParticipants} className={count === 4 ? 'selected' : ''} onClick={() => setCount(4)}>4 giocatori</button></div>{lockParticipants && <small>Il numero non può cambiare dopo la prima mano.</small>}</fieldset>
    <fieldset><legend>Posti in senso orario</legend><div className={`seat-preview seats-${count}`} aria-label="Disposizione al tavolo">{players.map((p, i) => <label className={`seat seat-${i}`} key={p.id}><span>{i + 1}</span><input aria-label={`Nome posto ${i + 1}`} value={names[i] ?? ''} onChange={e => setNames(v => v.map((x, j) => j === i ? e.target.value : x))} /></label>)}<div className="table-mark">↻</div></div></fieldset>
    <div className="form-grid"><label>Obiettivo individuale del Pozzo<input type="number" min="1" step="1" value={target} onChange={e => setTarget(Number(e.target.value))} /></label><label>Valore di un Credito in euro<input inputMode="decimal" value={euros} onChange={e => setEuros(e.target.value)} /></label></div>
    {count === 4 && <ChoiceButtons legend="Chi riposa nella prima mano?" options={players.map(p => ({ value: p.id, label: p.name }))} value={rest} onChange={setRest} />}
    {!valid && <p className="error" role="alert">Controlla nomi distinti, obiettivo positivo e valore del Credito.</p>}<div className="button-row">{onCancel && <button onClick={onCancel}>Annulla</button>}<button className="primary wide" disabled={!valid} onClick={() => setReview(true)}>Rivedi configurazione →</button></div>
  </> : <><div className="review-table">{players.map((p, i) => <div key={p.id}><span>Posto {i + 1}</span><strong>{p.name}</strong></div>)}<div><span>Obiettivo Pozzo</span><strong>{target}</strong></div><div><span>Un Credito</span><strong>{euro(config.euroCentsPerCredit)}</strong></div>{count === 4 && <div><span>Primo riposo</span><strong>{players.find(p => p.id === config.firstRestPlayerId)?.name}</strong></div>}</div><div className="button-row"><button onClick={() => setReview(false)}>← Modifica</button><button className="primary" onClick={() => onStart(config)}>Inizia la partita</button></div></>}</section></main>
}

function ScoreSheet({ state }: { state: GameState }) {
  const ids = state.config.players.map(p => p.id); const count = ids.length
  return <section className={`score-sheet score-${count}`} aria-label={`Tabellone tradizionale Preferans a ${count} giocatori`}>
    <svg className="score-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      {count === 3 ? <>
        <polygon points="50,4 96,94 4,94" />
        <polygon points="50,37 68,70 32,70" />
        <line x1="50" y1="4" x2="50" y2="37" />
        <line x1="96" y1="94" x2="68" y2="70" />
        <line x1="4" y1="94" x2="32" y2="70" />
      </> : <>
        <polygon points="50,3 97,50 50,97 3,50" />
        <polygon points="50,34 66,50 50,66 34,50" />
        <line x1="50" y1="3" x2="50" y2="34" />
        <line x1="97" y1="50" x2="66" y2="50" />
        <line x1="50" y1="97" x2="50" y2="66" />
        <line x1="3" y1="50" x2="34" y2="50" />
      </>}
    </svg>
    <div className="score-center"><span>MANO</span><strong>{state.applied.filter(a => a.event.type !== 'manual').length + 1}</strong></div>
    <div className="raspasy-corner">Raspasy ×{state.raspasyLevel}</div>
    {state.config.players.map((p, i) => <article className={`player-node node-${i} ${state.scores[p.id]!.pool === state.config.poolTarget ? 'closed' : ''}`} key={p.id}>
      <div className="player-name">{p.name}{state.nextRestPlayerId === p.id && <span className="rest-badge">riposa</span>}</div>
      <div className="score-pair"><span><small>POZZO</small><strong>{state.scores[p.id]!.pool}<i> / {state.config.poolTarget}</i></strong></span><span><small>MULTA</small><strong>{state.scores[p.id]!.penalty}</strong></span></div>
      <div className="credit-title">CREDITI</div><div className="credit-list">{ids.filter(id => id !== p.id).map(id => <span key={id} title={`${p.name} possiede Crediti verso ${nameOf(state, id)}`}><b>{nameOf(state, id)}</b>{formatFraction(state.credits[p.id]![id]!)}</span>)}</div>
    </article>)}
  </section>
}

type ButtonValue = string | number
function ChoiceButtons<T extends ButtonValue>({ legend, options, value, onChange, className = '' }: { legend: string; options: { value: T; label: string }[]; value: T; onChange: (value: T) => void; className?: string }) {
  return <fieldset className={`choice-field ${className}`}><legend>{legend}</legend><div className="button-options">{options.map(option => <button type="button" key={String(option.value)} className={value === option.value ? 'selected' : ''} aria-pressed={value === option.value} onClick={() => onChange(option.value)}>{option.label}</button>)}</div></fieldset>
}

interface WizardProps { stateBefore: GameState; initial?: GameEvent; onCancel: () => void; onSave: (e: GameEvent) => void }
function HandWizard({ stateBefore, initial, onCancel, onSave }: WizardProps) {
  const dialogRef = useRef<HTMLElement>(null)
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const dialog = dialogRef.current; dialog?.querySelector<HTMLElement>('.icon-button')?.focus(); const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onCancel(); if (e.key === 'Tab' && dialog) { const focusable = [...dialog.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),summary,a[href]')]; if (!focusable.length) return; const first = focusable[0]!, last = focusable.at(-1)!; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus() } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus() } } }; addEventListener('keydown', onKey); return () => { removeEventListener('keydown', onKey); previous?.focus() } }, [onCancel])
  const [step, setStep] = useState(1); const [type, setType] = useState<HandType>(initial?.type ?? 'normal'); const [restId, setRestId] = useState(initial?.restPlayerId ?? stateBefore.nextRestPlayerId)
  const active = activePlayers(stateBefore.config, stateBefore.config.players.length === 4 && type !== 'manual' ? restId : undefined); const firstActive = active[0]!
  const [declarerId, setDeclarer] = useState(initial && 'declarerId' in initial ? initial.declarerId : firstActive); const [level, setLevel] = useState<6 | 7 | 8 | 9 | 10>(initial?.type === 'normal' ? initial.level : 6); const [suit, setSuit] = useState<Suit>(initial?.type === 'normal' ? initial.suit : 'picche')
  const defenders = type === 'normal' && active.includes(declarerId) ? defenderOrder(stateBefore.config, active, declarerId) : undefined
  const [choices, setChoices] = useState<Record<string, DefenderChoice>>(initial?.type === 'normal' ? initial.defenderChoices : {}); const [tricks, setTricks] = useState<Record<string, number>>(initial && 'tricks' in initial && initial.tricks ? initial.tricks : {}); const [mizerTricks, setMizerTricks] = useState<number | undefined>(initial?.type === 'mizer' ? initial.declarerTricks : undefined)
  const [manualKind, setManualKind] = useState<'pool' | 'penalty' | 'credit'>(initial?.type === 'manual' ? initial.adjustments[0]?.kind ?? 'pool' : 'pool'); const [manualPlayer, setManualPlayer] = useState(initial?.type === 'manual' && initial.adjustments[0] && 'playerId' in initial.adjustments[0] ? initial.adjustments[0].playerId : stateBefore.config.players[0]!.id); const [manualAgainst, setManualAgainst] = useState(initial?.type === 'manual' && initial.adjustments[0] && 'againstId' in initial.adjustments[0] ? initial.adjustments[0].againstId : stateBefore.config.players[1]!.id); const [amount, setAmount] = useState(initial?.type === 'manual' ? initial.adjustments[0]?.amount ?? 1 : 1); const [note, setNote] = useState(initial?.note ?? ''); const [raspasyOverride, setRaspasyOverride] = useState<'' | 1 | 2 | 3>(initial?.type === 'manual' ? initial.raspasyLevel ?? '' : '')
  const selectedDeclarer = active.includes(declarerId) ? declarerId : firstActive
  const normalChoices = defenders ? { [defenders[0]]: choices[defenders[0]] ?? 'pass', [defenders[1]]: choices[defenders[1]] ?? 'pass' } : {}
  const playedNormal = type === 'normal' && defenders && !(normalChoices[defenders[0]] === 'pass' && normalChoices[defenders[1]] === 'pass')
  const passingDefender = playedNormal && defenders ? defenders.find(id => normalChoices[id] === 'pass') : undefined
  const displayedTricks = { ...tricks }
  if (passingDefender) { const countedPlayers = active.filter(id => id !== passingDefender); if (countedPlayers.every(id => tricks[id] !== undefined)) displayedTricks[passingDefender] = 10 - countedPlayers.reduce((sum, id) => sum + Number(tricks[id]), 0); else delete displayedTricks[passingDefender] }
  const makeEvent = (): GameEvent => { const base = { id: initial?.id ?? uid(), createdAt: initial?.createdAt ?? new Date().toISOString(), note: note || undefined }
    if (type === 'normal') { const ch = normalChoices as Record<string, DefenderChoice>; return { ...base, type, restPlayerId: restId, declarerId: selectedDeclarer, level, suit, defenderChoices: ch, tricks: playedNormal ? Object.fromEntries(active.map(id => [id, Number(displayedTricks[id] ?? 0)])) : undefined } }
    if (type === 'mizer') return { ...base, type, restPlayerId: restId, declarerId: selectedDeclarer, declarerTricks: Number(mizerTricks ?? 0) }
    if (type === 'raspasy') return { ...base, type, restPlayerId: restId, tricks: Object.fromEntries(active.map(id => [id, Number(tricks[id] ?? 0)])) }
    const adjustment: ManualAdjustment = manualKind === 'credit' ? { kind: 'credit', fromId: manualPlayer, againstId: manualAgainst, amount } : { kind: manualKind, playerId: manualPlayer, amount }
    return { ...base, type, adjustments: [adjustment], raspasyLevel: raspasyOverride || undefined }
  }
  let preview: GameState | undefined; let previewApplied: AppliedEvent | undefined; let error = ''
  if (type === 'normal' && playedNormal) { const required = active.filter(id => id !== passingDefender); if (required.some(id => tricks[id] === undefined)) error = 'Seleziona le prese del dichiarante e di chi ha scelto vist.' }
  if (type === 'mizer' && mizerTricks === undefined) error = 'Seleziona le prese del dichiarante.'
  if (type === 'raspasy' && active.some(id => tricks[id] === undefined)) error = 'Seleziona le prese di tutti i giocatori.'
  if (!error) try { preview = applyEvent(stateBefore, makeEvent()); previewApplied = preview.applied.at(-1) } catch (e) { error = e instanceof Error ? e.message : 'Dati non validi' }
  const canNext = step < 3 || !error
  const resetForType = (t: HandType) => { setType(t); setStep(2) }
  const changeRest = (id: string) => { setRestId(id); if (declarerId === id) setDeclarer(stateBefore.config.players.find(p => p.id !== id)!.id) }
  const playerOptions = (ids: string[]) => ids.map(id => ({ value: id, label: nameOf(stateBefore, id) }))
  const setChoice = (id: string, choice: DefenderChoice) => setChoices(current => ({ ...current, [id]: choice }))
  return <div className="modal-backdrop" role="presentation"><section ref={dialogRef} className="wizard" role="dialog" aria-modal="true" aria-labelledby="wizard-title"><header><div><p className="eyebrow">{initial ? 'Modifica evento' : 'Registra mano'} · passo {step} di 4</p><h2 id="wizard-title">{['Tipo di mano', 'Protagonisti', 'Esito e prese', 'Controlla le variazioni'][step - 1]}</h2></div><button className="icon-button" aria-label="Chiudi senza salvare" onClick={onCancel}>×</button></header><div className="progress"><i style={{ width: `${step * 25}%` }} /></div><div className="wizard-body">
    {step === 1 && <div className="choice-grid hand-type-grid">{([['normal', '♠', 'Contratto'], ['mizer', '◇', 'Mizer'], ['raspasy', '↘', 'Raspasy'], ['manual', '±', 'Correzione']] as const).map(([v, icon, label]) => <button key={v} onClick={() => resetForType(v)}><b>{icon}</b><span>{label}</span></button>)}</div>}
    {step === 2 && <div className="form-stack">
      {stateBefore.config.players.length === 4 && type !== 'manual' && <><ChoiceButtons legend="Chi riposa in questa mano?" options={playerOptions(stateBefore.config.players.map(p => p.id))} value={restId ?? stateBefore.config.players[3]!.id} onChange={changeRest} /><small className="field-help">Previsto: {nameOf(stateBefore, stateBefore.nextRestPlayerId)}</small></>}
      {(type === 'normal' || type === 'mizer') && <ChoiceButtons legend="Chi era il dichiarante?" options={playerOptions(active)} value={selectedDeclarer} onChange={setDeclarer} />}
      {type === 'normal' && <><ChoiceButtons legend="Livello" className="compact-options" options={[6, 7, 8, 9, 10].map(value => ({ value: value as typeof level, label: String(value) }))} value={level} onChange={setLevel} /><ChoiceButtons legend="Seme" className="suit-options" options={[{ value: 'picche' as Suit, label: '♠ Picche' }, { value: 'fiori' as Suit, label: '♣ Fiori' }, { value: 'quadri' as Suit, label: '♦ Quadri' }, { value: 'cuori' as Suit, label: '♥ Cuori' }, { value: 'senza briscola' as Suit, label: 'NT Senza atout' }]} value={suit} onChange={setSuit} /></>}
      {type === 'raspasy' && <div className="info-box">Nessun dichiarante. Valore di questa mano: <strong>{stateBefore.raspasyLevel} per presa</strong>.</div>}
      {type === 'manual' && <><ChoiceButtons legend="Voce da correggere" options={[{ value: 'pool' as const, label: 'Pozzo' }, { value: 'penalty' as const, label: 'Multa' }, { value: 'credit' as const, label: 'Crediti' }]} value={manualKind} onChange={setManualKind} /><ChoiceButtons legend={manualKind === 'credit' ? 'Chi possiede i Crediti?' : 'Giocatore'} options={playerOptions(stateBefore.config.players.map(p => p.id))} value={manualPlayer} onChange={setManualPlayer} />{manualKind === 'credit' && <ChoiceButtons legend="Contro chi?" options={playerOptions(stateBefore.config.players.filter(p => p.id !== manualPlayer).map(p => p.id))} value={manualAgainst} onChange={setManualAgainst} />}</>}
    </div>}
    {step === 3 && <div className="form-stack">
      {type === 'normal' && defenders && <><PlayerOutcome state={stateBefore} id={defenders[0]} choice={normalChoices[defenders[0]] as DefenderChoice} choices={['vist', 'pass']} onChoice={choice => setChoice(defenders[0], choice)} tricks={displayedTricks[defenders[0]]} onTricks={value => setTricks(current => ({ ...current, [defenders[0]]: value }))} disabled={(normalChoices[defenders[0]] ?? 'pass') === 'pass'} derived={passingDefender === defenders[0]} /><PlayerOutcome state={stateBefore} id={defenders[1]} choice={normalChoices[defenders[1]] as DefenderChoice} choices={level <= 7 && normalChoices[defenders[0]] === 'pass' ? ['vist', 'pass', 'polvist'] : ['vist', 'pass']} onChoice={choice => setChoice(defenders[1], choice)} tricks={displayedTricks[defenders[1]]} onTricks={value => setTricks(current => ({ ...current, [defenders[1]]: value }))} disabled={(normalChoices[defenders[1]] ?? 'pass') === 'pass'} derived={passingDefender === defenders[1]} />{playedNormal ? <TrickPicker label={`Prese di ${nameOf(stateBefore, selectedDeclarer)} · dichiarante`} value={tricks[selectedDeclarer]} onChange={value => setTricks(current => ({ ...current, [selectedDeclarer]: value }))} /> : <div className="info-box">Entrambi passano: la mano non viene giocata e non occorre inserire le prese.</div>} {playedNormal && <TotalTricks ids={active} values={displayedTricks} />}</>}
      {type === 'mizer' && <TrickPicker label={`Prese di ${nameOf(stateBefore, selectedDeclarer)} · dichiarante`} value={mizerTricks} onChange={setMizerTricks} />}
      {type === 'raspasy' && <TrickInputs state={stateBefore} ids={active} values={tricks} onChange={setTricks} />}
      {type === 'manual' && <><label>Variazione (usa il segno − per sottrarre)<input type="number" step="1" value={amount} onChange={e => setAmount(Number(e.target.value))} /></label><label>Motivazione facoltativa<input value={note} onChange={e => setNote(e.target.value)} placeholder="Es. correzione del tavolo" /></label><details><summary>Correggi anche la progressione Raspasy</summary><ChoiceButtons legend="Nuovo livello" options={[{ value: '' as const, label: 'Non modificare' }, { value: 1 as const, label: '1' }, { value: 2 as const, label: '2' }, { value: 3 as const, label: '3' }]} value={raspasyOverride} onChange={setRaspasyOverride} /><p className="warning">Questa modifica ricalcola tutte le mani successive.</p></details></>}
      {error && <p className="error" role="alert">{error}</p>}
    </div>}
    {step === 4 && previewApplied && <Preview applied={previewApplied} state={stateBefore} />}
  </div><footer><button onClick={() => step === 1 ? onCancel() : setStep(s => s - 1)}>{step === 1 ? 'Annulla' : '← Indietro'}</button>{step < 4 ? <button className="primary" disabled={!canNext} onClick={() => setStep(s => s + 1)}>Continua →</button> : <button className="primary" disabled={!!error} onClick={() => onSave(makeEvent())}>{initial ? 'Salva modifica' : 'Salva mano'}</button>}</footer></section></div>
}

function TrickPicker({ label, value, onChange, disabled = false, derived = false }: { label: string; value?: number; onChange: (value: number) => void; disabled?: boolean; derived?: boolean }) { return <fieldset className={`trick-picker ${disabled ? 'disabled' : ''}`}><legend>{label}</legend><div className="trick-buttons">{Array.from({ length: 11 }, (_, valueOption) => <button type="button" key={valueOption} disabled={disabled} className={value === valueOption ? 'selected' : ''} aria-pressed={value === valueOption} onClick={() => onChange(valueOption)}>{valueOption}</button>)}</div>{derived && <small>Calcolate automaticamente dal totale delle 10 prese.</small>}</fieldset> }
function PlayerOutcome({ state, id, choice, choices, onChoice, tricks, onTricks, disabled, derived }: { state: GameState; id: string; choice: DefenderChoice; choices: DefenderChoice[]; onChoice: (choice: DefenderChoice) => void; tricks?: number; onTricks: (value: number) => void; disabled: boolean; derived: boolean }) { return <section className="player-outcome"><h3>{nameOf(state, id)}</h3><div className="decision-buttons">{choices.map(option => <button type="button" key={option} className={choice === option ? 'selected' : ''} aria-pressed={choice === option} onClick={() => onChoice(option)}>{option}</button>)}</div><TrickPicker label="Prese" value={tricks} onChange={onTricks} disabled={disabled} derived={derived} /></section> }
function TotalTricks({ ids, values }: { ids: string[]; values: Record<string, number> }) { const total = ids.reduce((sum, id) => sum + Number(values[id] ?? 0), 0); return <p className={total === 10 ? 'total-ok' : 'error'}>Totale: {total}/10 {total === 10 ? '✓' : '— deve essere 10'}</p> }
function TrickInputs({ state, ids, values, onChange }: { state: GameState; ids: string[]; values: Record<string, number>; onChange: (v: Record<string, number>) => void }) { return <fieldset><legend>Prese dei giocatori attivi</legend><div className="tricks-stack">{ids.map(id => <TrickPicker key={id} label={nameOf(state, id)} value={values[id]} onChange={value => onChange({ ...values, [id]: value })} />)}</div><TotalTricks ids={ids} values={values} /></fieldset> }

function Preview({ applied, state }: { applied: AppliedEvent; state: GameState }) { const items = (record: Record<string, number>) => Object.entries(record).filter(([, v]) => v !== 0); return <div className="preview"><div className="preview-summary"><span>Risultato</span><strong>{applied.summary}</strong></div><section><h3>Pozzo</h3>{items(applied.poolChanges).length ? items(applied.poolChanges).map(([id, v]) => <p key={id}>{nameOf(state, id)} <b>{signed(v)}</b></p>) : <p>Nessuna variazione</p>}</section><section><h3>Multa</h3>{items(applied.penaltyChanges).length ? items(applied.penaltyChanges).map(([id, v]) => <p key={id}>{nameOf(state, id)} <b>{signed(v)}</b></p>) : <p>Nessuna variazione</p>}</section><section><h3>Crediti</h3>{applied.creditChanges.length ? applied.creditChanges.map((c, i) => <p key={i}>{nameOf(state, c.fromId)} → {nameOf(state, c.againstId)} <b>+{formatFraction(c.amount)}</b></p>) : <p>Nessuna variazione</p>}</section>{applied.aids.length > 0 && <section className="american-mini"><h3>🇺🇸 Aiuto americano</h3>{applied.aids.map((a, i) => <p key={i}><b>{nameOf(state, a.donorId)}</b> aiuta <b>{nameOf(state, a.recipientId)}</b>: {a.poolPoints} Pozzo, {a.credits} Crediti.</p>)}</section>}<div className="preview-meta"><span>Raspasy: {applied.raspasyBefore} → {applied.raspasyAfter}</span>{applied.nextRestPlayerId && <span>Prossimo riposo: {nameOf(state, applied.nextRestPlayerId)}</span>}</div></div> }

function tricksOf(applied: AppliedEvent) { const event = applied.event; if (event.type === 'normal') return event.tricks; if (event.type === 'raspasy') return event.tricks; if (event.type === 'mizer') return event.tricks ?? { [event.declarerId]: event.declarerTricks }; return undefined }
function tricksLabel(applied: AppliedEvent, state: GameState) { const tricks = tricksOf(applied); if (applied.event.type === 'normal' && !tricks) return 'Mano non giocata'; if (!tricks) return ''; return `Prese: ${applied.activeIds.filter(id => tricks[id] !== undefined).map(id => `${nameOf(state, id)} ${tricks[id]}`).join(' · ')}` }
function History({ state, onEdit, onDelete }: { state: GameState; onEdit: (index: number) => void; onDelete: (index: number) => void }) {
  const [filter, setFilter] = useState('all'); const visible = state.applied.map((a, i) => ({ a, i })).filter(({ a }) => filter === 'all' || a.event.type === filter || a.activeIds.includes(filter)); const filters = [{ value: 'all', label: 'Tutti' }, { value: 'normal', label: 'Contratti' }, { value: 'mizer', label: 'Mizer' }, { value: 'raspasy', label: 'Raspasy' }, { value: 'manual', label: 'Correzioni' }, ...state.config.players.map(p => ({ value: p.id, label: p.name }))]
  return <section className="page-section"><div className="section-heading"><div><p className="eyebrow">Registro immutabile</p><h2>Cronologia</h2></div></div><div className="history-filters" aria-label="Filtra cronologia">{filters.map(option => <button type="button" key={option.value} className={filter === option.value ? 'selected' : ''} aria-pressed={filter === option.value} onClick={() => setFilter(option.value)}>{option.label}</button>)}</div>{visible.length ? <div className="timeline">{[...visible].reverse().map(({ a, i }) => { const tricks = tricksOf(a); return <details className="history-item" key={a.event.id}><summary><span className={`event-icon ${a.event.type}`}>{a.event.type === 'normal' ? a.event.level : a.event.type === 'manual' ? '±' : a.event.type[0]}</span><span><b>{a.event.type === 'manual' ? 'Correzione' : `Mano ${a.handNumber}`}</b><small>{a.summary}</small><small className="history-tricks-inline">{tricksLabel(a, state)}</small></span><time>{new Date(a.event.createdAt).toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' })}</time></summary><div className="history-detail"><p>Attivi: {a.activeIds.map(id => nameOf(state, id)).join(', ')}{a.restPlayerId && ` · Riposa: ${nameOf(state, a.restPlayerId)}`}</p>{tricks ? <div className="history-tricks"><strong>Prese della mano</strong>{a.activeIds.filter(id => tricks[id] !== undefined).map(id => <span key={id}><b>{nameOf(state, id)}</b><em>{tricks[id]}</em></span>)}</div> : a.event.type === 'normal' && <div className="info-box">Entrambi hanno scelto pass: mano non giocata.</div>}<Preview applied={a} state={state} /><div className="button-row"><button onClick={() => onEdit(i)}>Modifica e ricalcola</button><button className="danger" onClick={() => onDelete(i)}>Elimina</button></div></div></details>})}</div> : <div className="empty-state">Nessun evento corrisponde al filtro.</div>}</section>
}

function Results({ state }: { state: GameState }) { const result = finalize(state); return <section className="page-section"><div className="section-heading"><div><p className="eyebrow">Bilancio esatto</p><h2>Risultato finale</h2></div><span className={state.completed ? 'status done' : 'status'}>{state.completed ? 'Tutti i Pozzi sono chiusi' : 'Proiezione corrente'}</span></div><p>Multa minima sottratta: <strong>{result.minimumPenalty}</strong>. Gli importi periodici restano frazioni esatte fino agli euro.</p><div className="ranking">{result.players.map((p, i) => <article key={p.playerId}><span className="rank">{i + 1}</span><div><h3>{nameOf(state, p.playerId)}</h3><p>Posseduti {formatFraction(p.grossOwned, 4)} · subiti {formatFraction(p.grossSuffered, 4)} · Multa residua {p.residualPenalty}</p></div><div className="result-values"><span><small>Crediti</small><strong className={p.netCredits.n >= 0 ? 'positive' : 'negative'}>{formatFraction(p.netCredits, 4)}</strong></span><span><small>Euro</small><strong className={p.euroCents >= 0 ? 'positive' : 'negative'}>{euro(p.euroCents)}</strong></span></div></article>)}</div><h3>Pagamenti minimi</h3><div className="payments">{result.payments.length ? result.payments.map((p, i) => <p key={i}><b>{nameOf(state, p.fromId)}</b> paga <strong>{euro(p.cents)}</strong> a <b>{nameOf(state, p.toId)}</b></p>) : <p>Nessun pagamento necessario.</p>}</div><div className="button-row"><button className="primary" onClick={() => exportPdf(state, false)}>Esporta PDF sintetico</button><button onClick={() => exportPdf(state, true)}>PDF con cronologia completa</button></div></section> }

function Manual() { const [query, setQuery] = useState(''); const [tag, setTag] = useState('tutti'); const tags = [...new Set(manualSections.flatMap(s => s.tags))]; const filtered = manualSections.filter(s => (tag === 'tutti' || s.tags.includes(tag)) && `${s.title} ${s.body.join(' ')} ${s.table?.flat().join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())); const mark = (text: string) => { if (!query.trim()) return text; const i = text.toLocaleLowerCase().indexOf(query.toLocaleLowerCase()); return i < 0 ? text : <>{text.slice(0, i)}<mark>{text.slice(i, i + query.length)}</mark>{text.slice(i + query.length)}</> }; const displayTag = (value: string) => value === 'mizer' ? 'Mizer' : value === 'raspasy' ? 'Raspasy' : value; return <section className="manual-layout"><aside><h2>Manuale</h2><input type="search" placeholder="Cerca una regola…" value={query} onChange={e => setQuery(e.target.value)} /><div className="tag-list"><button className={tag === 'tutti' ? 'selected' : ''} onClick={() => setTag('tutti')}>Tutto</button>{tags.map(t => <button className={tag === t ? 'selected' : ''} key={t} onClick={() => setTag(t)}>{displayTag(t)}</button>)}</div><nav>{filtered.map(s => <a href={`#manuale/${s.id}`} key={s.id}>{s.title}</a>)}</nav></aside><div className="manual-content"><p className="eyebrow">Regole del motore</p><h1>Manuale tecnico</h1><p className="lead">La fonte consultabile di ogni formula usata da Preferans Score.</p>{filtered.map(s => <article id={s.id} key={s.id}><h2>{mark(s.title)}</h2>{s.body.map((p, i) => <p key={i}>{mark(p)}</p>)}{s.table && <div className="table-scroll"><table><tbody>{s.table.map((r, i) => <tr key={i}>{r.map((c, j) => i === 0 || j === 0 ? <th key={j}>{mark(c)}</th> : <td key={j}>{mark(c)}</td>)}</tr>)}</tbody></table></div>}<a className="section-link" href={`#manuale/${s.id}`} aria-label={`Collegamento diretto a ${s.title}`}># collegamento diretto</a></article>)}{!filtered.length && <div className="empty-state">Nessuna regola trovata. Prova parole come “polvist” o “riposo”.</div>}</div></section> }

function Learn() { return <section className="learn-page"><header><p className="eyebrow">Da zero alla prima mano</p><h1>Impara a giocare</h1><p className="lead">Una guida visuale e semplice. L’app parte dal contratto finale: non simula l’asta completa.</p><div className="card-fan" aria-label="Esempio di carte dal 7 all'asso">{['7♣', '10♦', 'J♠', 'Q♥', 'K♣', 'A♠'].map(c => <i key={c}>{c}</i>)}</div></header><div className="learn-grid">{beginnerSections.map((s, i) => <article key={s.title}><span>{String(i + 1).padStart(2, '0')}</span><h2>{s.title}</h2><p>{s.text}</p>{[1, 4, 9].includes(i) && <aside><b>Ricorda</b>{i === 1 ? ' Segui sempre il seme, se puoi.' : i === 4 ? ' Pozzo bene, Multa male, Crediti contro qualcuno.' : ' L’app chiude i conti senza perdere un centesimo.'}</aside>}</article>)}</div><section className="glossary"><h2>Mini glossario</h2><dl><div><dt>presa</dt><dd>Le tre carte giocate in un giro.</dd></div><div><dt>briscola</dt><dd>Il seme che batte gli altri.</dd></div><div><dt>vist</dt><dd>Impegno a difendere il contratto.</dd></div><div><dt>tallone</dt><dd>Le due carte fuori dalle mani.</dd></div></dl></section></section> }

function DataPanel({ game, state, onImport, onEditConfig, onNew }: { game: SavedGame; state: GameState; onImport: (g: SavedGame) => void; onEditConfig: () => void; onNew: () => void }) { const input = useRef<HTMLInputElement>(null); const download = () => { const blob = new Blob([serializeGame(game)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `preferans-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(a.href) }; const read = async (f?: File) => { if (!f) return; try { onImport(deserializeGame(await f.text())) } catch (e) { alert(e instanceof Error ? e.message : 'Backup non valido') } }; return <section className="page-section"><p className="eyebrow">Solo sul dispositivo</p><h2>Dati e partita</h2><div className="data-cards"><article><h3>Backup locale</h3><p>Esporta tutti gli eventi in JSON o ripristina un backup. Nessun dato viene trasmesso.</p><div className="button-row"><button onClick={download}>Esporta backup</button><button onClick={() => input.current?.click()}>Importa backup</button><input ref={input} hidden type="file" accept="application/json" onChange={e => read(e.target.files?.[0])} /></div></article><article><h3>Configurazione e PDF</h3><p>Modifica nomi, obiettivo e valore del Credito con ricalcolo, oppure genera il riepilogo completo.</p><div className="button-row"><button onClick={onEditConfig}>Modifica configurazione</button><button onClick={() => exportPdf(state, true)}>Esporta PDF</button></div></article><article><h3>Nuova partita</h3><p>La partita attuale verrà rimossa soltanto dopo conferma. Esporta prima un backup se vuoi conservarla.</p><button className="danger" onClick={() => { if (confirm('Cancellare la partita locale e iniziarne una nuova?')) onNew() }}>Cancella e ricomincia</button></article></div></section> }

export default function App() {
  const [game, setGame] = useState<SavedGame | null>(() => { try { return loadGame() } catch { return null } }); const [route, setRoute] = useState(location.hash.slice(1).split('/')[0] || 'partita'); const [wizard, setWizard] = useState<{ index?: number } | null>(null); const [aid, setAid] = useState<AppliedEvent | null>(null); const [showSetup, setShowSetup] = useState(!game); const [update, setUpdate] = useState(false); const [mobileMenu, setMobileMenu] = useState(false)
  useEffect(() => { const h = () => { setRoute(location.hash.slice(1).split('/')[0] || 'partita'); setMobileMenu(false) }; addEventListener('hashchange', h); const u = () => setUpdate(true); addEventListener('pwa-update', u); return () => { removeEventListener('hashchange', h); removeEventListener('pwa-update', u) } }, [])
  useEffect(() => { if (game) saveGame(game) }, [game])
  const state = useMemo(() => { if (!game) return null; try { return replay(game.config, game.events) } catch { return null } }, [game])
  if (showSetup || !game || !state) return <Setup initial={game?.config} lockParticipants={!!game?.events.length} onCancel={game ? () => setShowSetup(false) : undefined} onStart={config => { try { const events = game?.events ?? []; replay(config, events); if (events.length && !confirm('La nuova configurazione ricalcolerà tutta la cronologia. Continuare?')) return; const next = { schemaVersion: 1 as const, config, events, undone: [], updatedAt: new Date().toISOString() }; setGame(next); setShowSetup(false); location.hash = 'partita' } catch (e) { alert(e instanceof Error ? e.message : 'Configurazione incompatibile con la cronologia') } }} />
  const commit = (event: GameEvent) => { const events = [...game.events]; if (wizard?.index !== undefined) events[wizard.index] = event; else events.push(event); const nextState = replay(game.config, events); const applied = nextState.applied.find(a => a.event.id === event.id); setGame({ ...game, events, undone: [], updatedAt: new Date().toISOString() }); setWizard(null); if (applied?.aids.length && game.config.animations) setAid(applied) }
  const editState = wizard?.index !== undefined ? replay(game.config, game.events.slice(0, wizard.index)) : state; const editing = wizard?.index !== undefined ? game.events[wizard.index] : undefined
  const undo = () => { if (!game.events.length) return; setGame({ ...game, events: game.events.slice(0, -1), undone: [game.events.at(-1)!, ...game.undone], updatedAt: new Date().toISOString() }) }; const redo = () => { if (!game.undone.length) return; setGame({ ...game, events: [...game.events, game.undone[0]!], undone: game.undone.slice(1), updatedAt: new Date().toISOString() }) }
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#partita"><span>♠</span>Preferans <b>Score</b></a><nav aria-label="Navigazione principale"><a className={route === 'partita' ? 'active' : ''} href="#partita">Partita</a><a className={route === 'cronologia' ? 'active' : ''} href="#cronologia">Cronologia</a><a className={route === 'risultato' ? 'active' : ''} href="#risultato">Risultato</a><a className={route === 'manuale' ? 'active' : ''} href="#manuale">Manuale</a><a className={route === 'impara' ? 'active' : ''} href="#impara">Impara</a><a className={route === 'dati' ? 'active' : ''} href="#dati">Dati</a></nav></header>{update && <div className="update-banner" role="status">È disponibile una nuova versione. I dati locali restano al sicuro.<button onClick={() => dispatchEvent(new Event('pwa-apply-update'))}>Aggiorna</button></div>}<main className={`app-main route-${route}`}>
    {route === 'partita' && <><section className="game-header"><div><p className="eyebrow">Obiettivo {state.config.poolTarget} · 1 Credito = {euro(state.config.euroCentsPerCredit)}</p><h1>{state.completed ? 'Tutti i Pozzi sono chiusi' : 'Partita in corso'}</h1>{state.config.players.length === 4 && <p>Riposa ora <b>{nameOf(state, state.nextRestPlayerId)}</b> · poi {nameOf(state, state.config.players[(state.config.players.findIndex(p => p.id === state.nextRestPlayerId) + 1) % 4]?.id)}</p>}</div><button className="primary record" onClick={() => setWizard({})}>＋ Registra mano</button></section><ScoreSheet state={state}/><section className="quick-actions"><button disabled={!game.events.length} onClick={undo}>↶ Annulla ultimo</button><button disabled={!game.undone.length} onClick={redo}>↷ Ripristina</button><a href="#cronologia">Vedi cronologia</a><a href="#manuale">Perché questo punteggio?</a></section>{state.completed && <div className="completed-callout"><span>✓</span><div><h2>Tutti i Pozzi sono chiusi</h2><p>Il risultato esatto e i pagamenti sono pronti.</p></div><a className="button primary" href="#risultato">Apri risultato</a></div>}</>}
    {route === 'cronologia' && <History state={state} onEdit={index => setWizard({ index })} onDelete={index => { if (confirm('Eliminare questo evento e ricalcolare tutte le mani successive?')) setGame({ ...game, events: game.events.filter((_, i) => i !== index), undone: [], updatedAt: new Date().toISOString() }) }} />}
    {route === 'risultato' && <Results state={state}/>} {route === 'manuale' && <Manual/>} {route === 'impara' && <Learn/>} {route === 'dati' && <DataPanel game={game} state={state} onImport={g => { try { replay(g.config, g.events); setGame(g); location.hash = 'partita' } catch (e) { alert(e instanceof Error ? e.message : 'Backup incoerente') } }} onEditConfig={() => setShowSetup(true)} onNew={() => { localStorage.removeItem(STORAGE_KEY); setGame(null); setShowSetup(true) }} />}
  </main><nav className="bottom-nav" aria-label="Navigazione mobile"><a className={route === 'partita' ? 'active' : ''} href="#partita"><b>◇</b>Partita</a><a className={route === 'cronologia' ? 'active' : ''} href="#cronologia"><b>↺</b>Storico</a><button className="record-mobile" aria-label="Registra mano" onClick={() => setWizard({})}>＋</button><a className={route === 'impara' ? 'active' : ''} href="#impara"><b>♧</b>Impara</a><button className={`nav-item ${['risultato', 'manuale', 'dati'].includes(route) ? 'active' : ''}`} aria-label="Apri il menu" aria-expanded={mobileMenu} aria-controls="mobile-menu" onClick={() => setMobileMenu(true)}><b>☰</b>Menu</button></nav>
    {mobileMenu && <div className="mobile-menu-backdrop" onClick={() => setMobileMenu(false)}><section className="mobile-menu" id="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu principale" onClick={e => e.stopPropagation()}><header><div><p className="eyebrow">Tutte le funzioni</p><h2>Menu</h2></div><button className="mobile-menu-close" aria-label="Chiudi il menu" onClick={() => setMobileMenu(false)}>×</button></header><nav className="mobile-menu-grid" aria-label="Tutte le sezioni" onClick={e => { if ((e.target as HTMLElement).closest('a')) setMobileMenu(false) }}><a className={route === 'partita' ? 'active' : ''} href="#partita"><b>◇</b><span><strong>Partita</strong><small>Tabellone e nuova mano</small></span></a><a className={route === 'cronologia' ? 'active' : ''} href="#cronologia"><b>↺</b><span><strong>Cronologia</strong><small>Mani e prese registrate</small></span></a><a className={route === 'risultato' ? 'active' : ''} href="#risultato"><b>∑</b><span><strong>Risultato</strong><small>Crediti, euro e pagamenti</small></span></a><a className={route === 'impara' ? 'active' : ''} href="#impara"><b>♧</b><span><strong>Impara</strong><small>Guida per iniziare a giocare</small></span></a><a className={route === 'manuale' ? 'active' : ''} href="#manuale"><b>?</b><span><strong>Manuale</strong><small>Regole complete e formule</small></span></a><a className={route === 'dati' ? 'active' : ''} href="#dati"><b>↓</b><span><strong>Dati</strong><small>Backup, PDF e configurazione</small></span></a></nav><div className="mobile-menu-actions"><button disabled={!game.events.length} onClick={() => { undo(); setMobileMenu(false) }}>↶ Annulla ultimo</button><button disabled={!game.undone.length} onClick={() => { redo(); setMobileMenu(false) }}>↷ Ripristina</button></div></section></div>}
    {wizard && <HandWizard stateBefore={editState} initial={editing} onCancel={() => setWizard(null)} onSave={commit}/>} {aid && <div className="american-overlay" role="status" onClick={() => setAid(null)}><div><span className="flag">★</span><p>Aiuto americano!</p>{aid.aids.map((a, i) => <strong key={i}>{nameOf(state, a.donorId)} aiuta {nameOf(state, a.recipientId)}<small>{a.poolPoints} Pozzo · {a.credits} Crediti</small></strong>)}<button onClick={() => setAid(null)}>Continua</button></div></div>}
  </div>
}
